### ISSUE TITLE
How is this project licensed?

### ISSUE THREAD

**Issue by rossng** [gaggle/exploring-the-monorepo#2]
Thanks for this repo and the series of articles, Jon! It would have taken me ages to figure all this stuff out on my own.

I'd like to reuse some of the pieces (particularly `pnpm-context`) for an AGPL v3-licensed project, but it's not currently clear how the code here is licensed. Would you be able to indicate how it can be reused?

**Comment by gaggle** [comment]
Ah right, thanks, I forgot to add a license. I've done so now, the whole project is supposed to be free and public 👍

**Comment by rossng** [comment]
Thank you! <3
